// frontend/src/routes/collections/index.svelte
<script context="module" lang="ts">
	import AlbumPreview from '$lib/album/album-preview.svelte';
	import type { Album,Manifest } from '$lib/types';
	import type { Load } from '@sveltejs/kit';

	let collections: Album[];
	export const load: Load = function ({ stuff }) {
		let manifest: Manifest = stuff.manifest;
		collections = manifest.albums.filter((x) => !x.isPortfolio);

		return {};
	};
</script>

<div>
	<div class="collection-list">
		{#each collections as collection}
			<AlbumPreview album={collection} />
		{/each}
	</div>
</div>

// frontend-ng/src/app/components/collections/collections.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { getRouteData } from 'src/app/getRouteParam.function';
import { Album, Manifest } from 'src/app/types';

@Component({
  selector: 'app-collections',
  templateUrl: './collections.component.html',
  styleUrls: ['./collections.component.scss']
})
export class CollectionsComponent {
  albums: Album[];
  constructor(route: ActivatedRoute) {
    const manifest: Manifest = getRouteData(route.snapshot, 'manifest');
    this.albums = manifest.albums.filter(x => !x.isPortfolio);
  }

}

<div>
  <div class="collection-list">
    @for (album of albums; track album.id) {
      <app-album-preview [album]="album"></app-album-preview>
    }
  </div>
</div>
