// frontend-ng/src/app/components/about/about.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-about',
    templateUrl: './about.component.html',
    styleUrls: ['./about.component.scss'],
    standalone: true
})
export class AboutComponent {

}

<div class="content">
  <div class="blurb">
    <h2>Hi. I'm Logan.</h2>
    <p>
      I'm a full time software engineer, starting in 2013, with a strong technical background in
      .NET and MSSQL. I have a passion for helping others realise their potential and enjoy
      mentorship and elevating the abilities of my peers.
    </p>
    <p>Born in Johannesburg, South Africa, I relocated to Amsterdam, Netherlands in 2022.</p>
    <p>
      I am presently employed as a Senior Software Engineer at
      <a href="https://entelect.nl/" rel="nofollow noopener" target="_blank"
        >Entelect Netherlands</a
      >
      but this website and the views depicted on it are entirely my own.
    </p>
    <p>
      I'm a hobbyist photographer in my free time. I enjoy capturing depth, colour, and detail, and
      frequently use my photography to express my emotions.
    </p>
    <h3>My story</h3>
    <p>
      I have been interested in computers for as long as I can remember. My parents used to call me
      square eyes because of how much time I spent in front of a computer screen. I absorb knowledge
      on topics that interest me, so I quickly learnt how to use a computer and then spent the
      greater part of my childhood gaming!
    </p>
    <p>
      I started out learning how to create maps in Warcraft III, then later on made gamemodes and
      scripts in Grand Theft Auto
      <a href="https://www.sa-mp.com/" target="_blank" rel="nofollow noopener"
        >San Andreas Multiplayer</a
      >
      to play with my friends. That sparked an interest in how regular old applications were made,
      and I started teaching myself C# and C++, writing little applications just to see what I could
      do with them.
    </p>
    <p>
      By the end of high school I knew that I wanted to write code, so I applied to study Computer
      Science at a few universities. I landed up studying a Computer Systems degree through what was
      then known as CTI (which subsequently merged with Pearson Institute of Higher Education and is
      now known as
      <a href="https://www.eduvos.com/" rel="nofollow noopener" target="_blank">Eduvos</a>).
    </p>
    <p>
      Not long after figuring out how much I love code, I figured out I have a love for photography
      as well. I bought my first DSLR (A Canon EOS 1200D) for a trip to Europe in 2014 and have been
      enjoying it as a hobby since.
    </p>
    <p>I enjoy capturing images that give me inspiration and let me express my feelings.</p>
    <h3>Portfolio</h3>
    <p>
      This website is intended to be a portfolio of my creative work. It is entirely written by
      myself (save for some lovely
      <a href="https://shoelace.style" rel="nofollow noopener" target="_blank">Shoelace</a>
      components), with the source available
      <a href="https://github.com/biltongza/ldam.co.za" rel="nofollow nooopener" target="_blank"
        >on Github</a
      >. The photography on this site is synchronised from
      <a
        href="https://www.adobe.com/products/photoshop-lightroom.html"
        target="_blank"
        rel="nofollow noopener"
        >Adobe Lightroom</a
      >
      because I'm lazy and don't like having to manage image files :)
    </p>
  </div>
  <div class="secondary">
    <img src="/assets/Selfie.jpg" class="selfie" alt="Portrait of Logan Dam" />
    <div class="badges">
      <div
        data-iframe-width="150"
        data-iframe-height="270"
        data-share-badge-id="34a1f527-c255-4aba-a7cf-02489df0e272"
        data-share-badge-host="https://www.credly.com"
      ></div>
      <div
        data-iframe-width="150"
        data-iframe-height="270"
        data-share-badge-id="8b11351f-ac21-4194-a667-1cf559428d97"
        data-share-badge-host="https://www.credly.com"
      ></div>
      <script
        type="text/javascript"
        async
        src="//cdn.credly.com/assets/utilities/embed.js"
      ></script>
    </div>
  </div>
</div>

// frontend/src/routes/about/+page.svelte
<div class="content">
  <div class="blurb">
    <h2>Hi. I'm Logan.</h2>
    <p>
      I'm a full time software engineer, starting in 2013, with a strong technical background in
      .NET and MSSQL. I have a passion for helping others realise their potential and enjoy
      mentorship and elevating the abilities of my peers.
    </p>
    <p>Born in Johannesburg, South Africa, I relocated to Amsterdam, Netherlands in 2022.</p>
    <p>
      I am presently employed as a Senior Software Engineer at <a
        href="https://entelect.nl/"
        rel="nofollow noopener"
        target="_blank">Entelect Netherlands</a
      > but this website and the views depicted on it are entirely my own.
    </p>
    <p>
      I'm a hobbyist photographer in my free time. I enjoy capturing depth, colour, and detail, and
      frequently use my photography to express my emotions.
    </p>
    <h3>My story</h3>
    <p>
      I have been interested in computers for as long as I can remember. My parents used to call me
      square eyes because of how much time I spent in front of a computer screen. I absorb knowledge
      on topics that interest me, so I quickly learnt how to use a computer and then spent the
      greater part of my childhood gaming!
    </p>
    <p>
      I started out learning how to create maps in Warcraft III, then later on made gamemodes and
      scripts in Grand Theft Auto <a
        href="https://www.sa-mp.com/"
        target="_blank"
        rel="nofollow noopener">San Andreas Multiplayer</a
      > to play with my friends. That sparked an interest in how regular old applications were made,
      and I started teaching myself C# and C++, writing little applications just to see what I could
      do with them.
    </p>
    <p>
      By the end of high school I knew that I wanted to write code, so I applied to study Computer
      Science at a few universities. I landed up studying a Computer Systems degree through what was
      then known as CTI (which subsequently merged with Pearson Institute of Higher Education and is
      now known as <a href="https://www.eduvos.com/" rel="nofollow noopener" target="_blank"
        >Eduvos</a
      >).
    </p>
    <p>
      Not long after figuring out how much I love code, I figured out I have a love for photography
      as well. I bought my first DSLR (A Canon EOS 1200D) for a trip to Europe in 2014 and have been
      enjoying it as a hobby since.
    </p>
    <p>I enjoy capturing images that give me inspiration and let me express my feelings.</p>
    <h3>Portfolio</h3>
    <p>
      This website is intended to be a portfolio of my creative work. It is entirely written by
      myself (save for some lovely <a
        href="https://shoelace.style"
        rel="nofollow noopener"
        target="_blank">Shoelace</a
      >
      components), with the source available
      <a href="https://github.com/biltongza/ldam.co.za" rel="nofollow nooopener" target="_blank"
        >on Github</a
      >. The photography on this site is synchronised from
      <a
        href="https://www.adobe.com/products/photoshop-lightroom.html"
        target="_blank"
        rel="nofollow noopener">Adobe Lightroom</a
      > because I'm lazy and don't like having to manage image files :)
    </p>
  </div>
  <div class="secondary">
    <img src="/Selfie.jpg" class="selfie" alt="Portrait of Logan Dam" />
    <div class="badges">
      <div
        data-iframe-width="150"
        data-iframe-height="270"
        data-share-badge-id="34a1f527-c255-4aba-a7cf-02489df0e272"
        data-share-badge-host="https://www.credly.com"
      />
      <div
        data-iframe-width="150"
        data-iframe-height="270"
        data-share-badge-id="8b11351f-ac21-4194-a667-1cf559428d97"
        data-share-badge-host="https://www.credly.com"
      />
      <script
        type="text/javascript"
        async
        src="//cdn.credly.com/assets/utilities/embed.js"
      ></script>
    </div>
  </div>
</div>

<style>
  .content {
    max-width: 900px;
    margin-left: auto;
    margin-right: auto;
    display: flex;
    gap: 1rem;
    flex-direction: column;
  }
  @media only screen and (min-width: 1224px) {
    .content {
      flex-direction: row;
    }
  }

  .selfie {
    max-width: 100%;
    max-height: 70vh;
    object-fit: cover;
    margin-left: auto;
    margin-right: auto;
  }

  .secondary {
    width: 100%;
    text-align: center;
  }
  .badges {
    display: inline-block;
  }
</style>
