// frontend/src/lib/header/header.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import RouterLink from './router-link.svelte';
	import SocialIcon from './social-icon.svelte';
	let smol = false;
	let expanded = false;
	onMount(() => {
		const matchListener = (event: MediaQueryListEvent) => {
			smol = event.matches;
		};
		const mql = window.matchMedia('(max-width: 550px)');
		smol = mql.matches;
		mql.addEventListener('change', matchListener);
		return () => {
			mql.removeEventListener('change', matchListener);
		};
	});

	const routes = [
		{ label: 'About', path: '/about' },
		{ label: 'Collections', path: '/collections' },
		{ label: 'Blog', path: '/blog' }
	];

	const socials = [
		{ text: 'GitHub', label: 'github', href: 'https://github.com/biltongza', icon: 'github' },
		{
			text: 'LinkedIn',
			label: 'linkedin',
			href: 'https://www.linkedin.com/in/logan-dam/',
			icon: 'linkedin'
		},
		{
			text: 'Instagram',
			label: 'instagram',
			href: 'https://www.instagram.com/thebiltong/',
			icon: 'instagram'
		},
		{ text: 'Twitter', label: 'twitter', href: 'https://twitter.com/TheBiltong', icon: 'twitter' }
	];
</script>

<header class="header">
	<div class="nav-container">
		<a class="brand" href="/"><h1>Logan Dam</h1></a>
		<nav class={smol && expanded ? 'expanded' : ''}>
			<ul>
				{#if smol}
					<li><RouterLink path="/">Home</RouterLink></li>
				{/if}
				{#each routes as { label, path }}
					<li><RouterLink {path}>{label}</RouterLink></li>
				{/each}
				{#each socials as { text, label, href, icon }}
					<li>
						<SocialIcon {text} {label} {href} {icon} showText={smol && expanded} />
					</li>
				{/each}
			</ul>
		</nav>
	</div>
	{#if smol}
		<sl-icon-button
			class={`menu-button ${expanded ? 'expanded' : ''}`}
			name="chevron-double-down"
			on:click={() => (expanded = !expanded)}
		/>
	{/if}
</header>

<style lang="scss">
	:root {
		--header-height: 60px;
	}

	h1 {
		text-transform: uppercase;
		font-size: 100%;
	}

	.header {
		padding-left: var(--sl-spacing-small);
		padding-right: var(--sl-spacing-small);
		background-color: var(--sl-color-neutral-100);
		margin-bottom: var(--sl-spacing-small);
		display: flex;
		flex-direction: row;
		align-items: start;

		@media only screen and (min-width: 1224px) {
			padding-left: var(--sl-spacing-2x-large);
			padding-right: var(--sl-spacing-2x-large);
		}
	}

	.nav-container {
		flex: 1 0 auto;
		display: flex;
		flex-direction: row;
		justify-content: space-between;
		align-items: center;
		@media screen and (max-width: 550px) {
			flex-direction: column;
			align-items: flex-start;
			font-size: var(--sl-font-size-large);
		}
	}

	.brand,
	.menu-button {
		margin-top: var(--sl-spacing-small);
		margin-bottom: var(--sl-spacing-small);
		font-size: var(--sl-font-size-x-large);
	}

	.menu-button {
		flex: 0 0 auto;
		margin-top: var(--sl-spacing-large);
	}

	nav {
		@media screen and (max-width: 550px) {
			margin-bottom: var(--sl-spacing-medium);
			display: none;
			background-color: var(--sl-color-neutral-150);
			&.expanded {
				display: unset;
				width: 100%;
				ul {
					flex-direction: column;
					align-items: flex-end;
				}
			}
		}
		ul {
			list-style: none;
			display: flex;
			flex-direction: row;
			align-items: center;
			gap: var(--sl-spacing-medium);
			padding-inline-start: 0;
			margin: 0;
			li {
				min-height: 30px;
				display: flex;
				flex-direction: row;
				align-items: center;
			}
		}
	}
	.menu-button {
		display: none;
		@media only screen and (max-width: 550px) {
			display: block;
			transform: rotate(0deg);
			transition: all 0.25s ease-in;

			&.expanded {
				transform: rotate(180deg);
				transition: all 0.25s ease-out;
			}
		}
	}
</style>

// frontend-ng/src/app/components/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent {
  smol = false;
  expanded = false;

  routes = [
		{ label: 'About', path: '/about' },
		{ label: 'Collections', path: '/collections' },
		{ label: 'Blog', path: '/blog' }
	];

	socials = [
		{ text: 'GitHub', label: 'github', href: 'https://github.com/biltongza', icon: 'github' },
		{
			text: 'LinkedIn',
			label: 'linkedin',
			href: 'https://www.linkedin.com/in/logan-dam/',
			icon: 'linkedin'
		},
		{
			text: 'Instagram',
			label: 'instagram',
			href: 'https://www.instagram.com/thebiltong/',
			icon: 'instagram'
		},
		{ text: 'Twitter', label: 'twitter', href: 'https://twitter.com/TheBiltong', icon: 'twitter' }
	];

	toggle() {
		this.expanded = !this.expanded;
	}
}

<header class="header">
    <div class="nav-container">
        <a class="brand" href="/">
            <h1>Logan Dam</h1>
        </a>
        <nav [class.expanded]="smol && expanded">
            <ul>
                <li *ngIf="smol"><app-router-link path="/">Home</app-router-link></li>
                <li *ngFor="let route of routes"><app-routerlink [path]="route.path">{{route.label}}</app-routerlink>
                </li>
                <li *ngFor="let social of socials">
                    <app-social-icon [text]="social.text" [label]="social.label" [href]="social.href"
                        [icon]="social.icon" [showText]="smol && expanded" />
                </li>

            </ul>
        </nav>
    </div>
    <sl-icon-button *ngIf="smol" class="menu-button" [class.expanded]="expanded" name="chevron-double-down"
        [onClick]="toggle()" />
</header>
