// frontend/src/lib/footer/footer.svelte
<script>
	export const appver = __VERSION__;
	export const lastmod = __LASTMOD__;
</script>

<div class="footer">
	<p>
		made by <a href="https://github.com/biltongza/ldam.co.za" target="_blank" rel="nofollow noopener">me</a
		>
	</p>
	<div class="version"><span>{appver}</span>&nbsp;|<span>&nbsp;{lastmod}</span></div>
</div>

<style>
	.footer {
		padding-top: 2em;
		padding-bottom: 2em;
		display: flex;
		background-color: var(--sl-color-neutral-100);
		flex-direction: column;
		align-items: center;
        color: var(--sl-color-neutral-600);
        font-size: var(--sl-font-size-x-small);
        font-weight: var(--sl-font-weight-light);
	}
</style>

// frontend-ng/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-footer',
	templateUrl: './footer.component.html',
	styleUrls: ['./footer.component.scss'],
	standalone: true
})
export class FooterComponent {}

<div class="footer">
	<p>
		made by
		<a href="https://github.com/biltongza/ldam.co.za" target="_blank" rel="nofollow noopener">me</a>
	</p>
</div>
