// frontend-ng/src/app/components/album-preview/album-preview.component.ts
import { Component, Input, OnChanges, SimpleChanges } from "@angular/core";
import { Album, ImageMetadata } from "src/app/types";

@Component({
  selector: "app-album-preview",
  templateUrl: "./album-preview.component.html",
  styleUrls: ["./album-preview.component.scss"],
})
export class AlbumPreviewComponent implements OnChanges {
  @Input() album?: Album;
  @Input() numberOfImages: number = Number.MAX_SAFE_INTEGER;

  images?: ImageMetadata[];

  ngOnChanges(changes: SimpleChanges): void {
    if ((changes["album"] || changes["numberOfImages"]) && this.album) {
      const entries = Object.entries(this.album.images).map(([, meta]) => meta);
      this.images = entries
        .sort((meta1, meta2) => {
          const a = new Date(meta1.captureDate).valueOf();
          const b = new Date(meta2.captureDate).valueOf();

          return Number(b > a) - Number(b < a);
        })
        .slice(0, this.numberOfImages);
    }
  }

  getClassList(image: ImageMetadata): string {
    const parts = image.aspectRatio.split(":").map((part) => +part);
    const isLandscape = parts[0] > parts[1];
    return `thumbnail ${isLandscape ? "span-col" : ""}`;
  }
}

@if (album) {
  <section class="album-container">
    <h2>{{ album.title }}</h2>
    <div class="thumbnails">
      @for (image of images; track image) {
        <div [class]="getClassList(image)">
          <app-thumbnail [image]="image" />
        </div>
      }
    </div>
  </section>
}

// frontend/src/lib/album-preview.svelte
<script lang="ts">
	import type { Album,ImageMetadata } from './manifest';
	import Thumbnail from './thumbnail.svelte';
	export let album: Album;
	export let numberOfImages: number = Number.MAX_SAFE_INTEGER;

	const entries = Object.entries(album.images).map(([, meta]) => meta);
	const images = entries
		.sort((meta1, meta2) => {
			const a = new Date(meta1.captureDate).valueOf();
			const b = new Date(meta2.captureDate).valueOf();

			return Number(b > a) - Number(b < a);
		})
		.slice(0, numberOfImages);

	function getClassList(image: ImageMetadata): string {
		const parts = image.aspectRatio.split(':').map(part => +part);
		const isLandscape = parts[0] > parts[1];
		return `thumbnail ${isLandscape ? 'span-col' : ''}`
	}
</script>

<div class="album-container">
	<h3>{album.title}</h3>
	<div class="thumbnails">
		{#each images as image (image.id)}
			<div class={getClassList(image)} >
				<Thumbnail {image} />
			</div>
		{/each}
	</div>
</div>

<style>
	:root {
		--thumbnail-width: 500px
	}
	.thumbnails {
		line-height: 0;
		display: grid;
		column-gap: var(--sl-spacing-small);
		row-gap: var(--sl-spacing-small);
		place-items: center;
		justify-content: center;
		grid-auto-flow: dense;
	}

	.thumbnail.span-col {
		grid-column: span 2;
	}
	
	.thumbnail:hover {
		transform: scale(1.02);
	}

	@media only screen and (max-width: 640px) {
		.thumbnail.span-col {
			grid-column: initial;
		}
	}

	@media only screen and (min-width: 768px) {
		.thumbnails {
			grid-template-columns: repeat(3, fit-content(var(--thumbnail-width)));
		}
	}

	@media only screen and (min-width: 1030px) {
		.thumbnails {
			grid-template-columns: repeat(4, fit-content(var(--thumbnail-width)));
		}
	}

	@media only screen and (min-width: 1200px) {
		.thumbnails {
			grid-template-columns: repeat(5, fit-content(var(--thumbnail-width)));
		}
	}
</style>
