// frontend-ng/src/app/components/thumbnail/thumbnail.component.ts
import { Component, Input, OnChanges, SimpleChanges } from "@angular/core";
import { StorageBaseUrl, ThumbnailHrefNormalDensity } from "src/app/consts";
import { ImageMetadata } from "src/app/types";

const thumbnailSizes = {
  thumbnail2x: '320w',
  '640': '640w',
  '1280': '1280w'
};

// order is important here apparently
const formats = {
  webp: 'image/webp',
  jpg: 'image/jpeg',
};

@Component({
  selector: "app-thumbnail",
  templateUrl: "./thumbnail.component.html",
  styleUrls: ["./thumbnail.component.scss"],
})
export class ThumbnailComponent implements OnChanges {
  @Input() image?: ImageMetadata = undefined;
  imageRoute?: string;

  src?: string;
  srcSets: { srcSet: string; mime: string }[] = [];
  

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["image"] && this.image) {
      this.imageRoute = `/image/${this.image.id}`;
      this.src = `${StorageBaseUrl}/${this.image.hrefs[ThumbnailHrefNormalDensity]}.webp`;
      this.srcSets = Object.entries(thumbnailSizes).flatMap(
        ([sizeKey, maxWidth]) =>
          Object.entries(formats).map(([extension, mime]) => ({
            srcSet: `${StorageBaseUrl}/${this.image!.hrefs[sizeKey]}.${extension} ${maxWidth}`,
            mime,
          }))
      );
    }
  }
}

<a [routerLink]="imageRoute">
    <picture>
        <source *ngFor="let srcset of srcSets" [srcset]=srcset.srcSet [type]="srcset.mime" />
        <img [src]="src" class="thumbnail-image" loading="lazy" alt="" />
    </picture>
</a>

// frontend/src/lib/thumbnail.svelte
<script context="module" lang="ts">
	const thumbnailSizes = {
		thumbnail2x: '320w',
		'640': '640w',
		'1280': '1280w',
	};
</script>

<script lang="ts">
	import type { ImageMetadata } from './types';
	import {
	StorageBaseUrl,
	ThumbnailHrefNormalDensity
	} from './__consts';

	export let image: ImageMetadata = undefined;
	let imageRoute: string;
	let src: string;
	let srcSet: string;

	$: {
		imageRoute = `/image/${image.id}`;
		src = `${StorageBaseUrl}/${image.hrefs[ThumbnailHrefNormalDensity]}`;
		srcSet = Object.entries(thumbnailSizes).map(([key, value]) => `${StorageBaseUrl}/${image.hrefs[key]} ${value}`).join(', ');
	}
</script>

<a href={imageRoute}>
	<img {src} class="thumbnail-image" loading="lazy" alt="" {srcSet}/>
</a>

<style>
	a {
		display: block;
		width: 100%;
		height: 100%;
	}
	.thumbnail-image {
		width: 100%;
		height: 100%;
		object-fit: contain;
		max-height: 85vh;
		background-image: url('/tail-spin.svg');
		background-repeat: no-repeat;
		background-position: center;
	}
</style>
